version: '3.9'

services:
  workspace:
    container_name: ${PROJECT_NAME:-spring}-workspace
    build:
      context: ./docker/workspace
      args:
        USER_NAME: ${USER_NAME:-root}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    tty: true
    ports:
      - 5555:5555
    volumes:
      - ..:/home/vscode/workspace:cached
  pgsql:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: springdb
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "9090:8080"

